/**
 * apRecurring.ts — P1-d Recurring auto-pay (Melio-inspired AP suite)
 *
 * Router: apRecurringRouter
 *  - createSchedule  — idempotent (withIdempotency, REQUIRED key min 8);
 *      computes the first next_run_at from startAt + frequency.
 *  - listSchedules / getSchedule — merchant-scoped reads.
 *  - updateSchedule — guarded UPDATE ... WHERE id AND merchantId RETURNING;
 *      only is_active, max_amount_kobo, auto_approve_below_kobo, next_run_at
 *      are mutable (template/frequency are immutable after creation).
 *  - cancelSchedule — guarded is_active flip (active → inactive).
 *  - runHistory — bills generated by a schedule
 *      (ap_bills.source_ref LIKE 'recurring:{scheduleId}:%').
 *  - triggerNow — idempotent manual run of ONE schedule through the SAME
 *      core executor the cron sweep uses (executeRecurringScheduleRun in
 *      server/cronJobs.ts): claim-first (guarded run_count increment +
 *      next_run_at advance), then generate the bill.
 *
 * Conventions (IMPLEMENTATION_SPEC_MELIO.md §D1–D8, §P1-d):
 *  - merchant identity ALWAYS resolved server-side from ctx.user.openId
 *    (crud119.ts:110 resolveMerchantId pattern) — never from client input
 *  - money as bigint kobo; withIdempotency on create/trigger mutations
 *  - Kafka paygate.ap.bills (non-fatal) + auditLog() after mutations
 *  - The schedule executor itself lives in server/cronJobs.ts
 *    (processRecurringBillSchedules) and inserts ap_bills rows directly via
 *    drizzle — it does NOT import apBillPay (no cross-router coupling).
 */

import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { eq, and, desc, like, sql } from "drizzle-orm";
import { router, protectedProcedure } from "../_core/trpc";
import { getDb, getUserByOpenId, getMerchantByOwnerId } from "../db";
import { apRecurringSchedules, apBills } from "../../drizzle/schema";
import { withIdempotency } from "../idempotency";
import { publishEvent } from "../kafkaClient";
import { auditLog } from "../auditTrail";
import { logger } from "../logger";
import { executeRecurringScheduleRun } from "../cronJobs";

type DbHandle = NonNullable<Awaited<ReturnType<typeof getDb>>>;

const AP_BILL_TOPIC = "paygate.ap.bills";

// ─── Merchant resolution (server-side session only — never client input) ─────
// Same pattern as crud119.ts:110 resolveMerchantId.
async function resolveMerchant(openId: string) {
  const user = await getUserByOpenId(openId);
  if (!user) throw new TRPCError({ code: "UNAUTHORIZED", message: "User not found" });
  const merchant = await getMerchantByOwnerId(user.id);
  if (!merchant) throw new TRPCError({ code: "FORBIDDEN", message: "Merchant account required" });
  return { user, merchant };
}

async function requireDb(): Promise<DbHandle> {
  const db = await getDb();
  if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });
  return db;
}

// ─── Frequency helpers (pure — exported for tests) ───────────────────────────

export type RecurringFrequency = "weekly" | "monthly" | "quarterly";

function addFrequency(date: Date, frequency: RecurringFrequency): Date {
  const d = new Date(date.getTime());
  if (frequency === "weekly") d.setUTCDate(d.getUTCDate() + 7);
  else if (frequency === "monthly") d.setUTCMonth(d.getUTCMonth() + 1);
  else d.setUTCMonth(d.getUTCMonth() + 3); // quarterly
  return d;
}

/**
 * First next_run_at for a new schedule: startAt when it is in the future,
 * otherwise the first frequency-aligned slot strictly after `now`.
 */
function computeFirstNextRunAt(frequency: RecurringFrequency, startAt: Date, now: Date = new Date()): Date {
  let next = new Date(startAt.getTime());
  // A startAt far in the past walks forward one period at a time; bounded by
  // construction (weekly over 20 years ≈ 1043 iterations).
  while (next <= now) next = addFrequency(next, frequency);
  return next;
}

/** SQL fragment advancing next_run_at by frequency from the LATER of the
 *  current slot and NOW() — an overdue schedule must land on a FUTURE slot
 *  (same GREATEST reasoning as the SIP claim in cronJobs.ts). */
function nextRunAdvanceExpr() {
  return sql`CASE ${apRecurringSchedules.frequency}
    WHEN 'weekly'    THEN GREATEST(COALESCE(${apRecurringSchedules.nextRunAt}, NOW()), NOW()) + INTERVAL '7 days'
    WHEN 'quarterly' THEN GREATEST(COALESCE(${apRecurringSchedules.nextRunAt}, NOW()), NOW()) + INTERVAL '3 months'
    ELSE GREATEST(COALESCE(${apRecurringSchedules.nextRunAt}, NOW()), NOW()) + INTERVAL '1 month'
  END`;
}

// ─── Non-fatal side effects ──────────────────────────────────────────────────

async function publishScheduleEvent(
  type: string,
  merchantId: string,
  scheduleId: number,
  extra: Record<string, unknown> = {},
): Promise<void> {
  try {
    await publishEvent(
      AP_BILL_TOPIC,
      { type, merchantId, scheduleId, at: new Date().toISOString(), ...extra },
      `recurring:${scheduleId}`,
    );
  } catch (err) {
    logger.warn("ap_recurring_event_publish_failed", {
      type, scheduleId, error: err instanceof Error ? err.message : String(err),
    });
  }
}

async function auditSchedule(
  ctx: { user: { openId: string; name?: string | null; email?: string | null } },
  merchantId: string,
  action: string,
  scheduleId: number,
  metadata: Record<string, unknown> = {},
): Promise<void> {
  await auditLog({
    merchantId,
    actorId: ctx.user.openId,
    actorName: ctx.user.name ?? ctx.user.openId,
    actorEmail: ctx.user.email ?? undefined,
    action,
    resource: "ap_recurring_schedule",
    resourceId: String(scheduleId),
    metadata,
  });
}

// ─── Validation schemas ───────────────────────────────────────────────────────

const idempotencyKeySchema = z.string().min(8).max(128);

const lineItemInput = z.object({
  description: z.string().min(1).max(2000),
  quantity: z.number().positive(),
  unitPriceKobo: z.number().int().nonnegative(),
  amountKobo: z.number().int().nonnegative().optional(),
  accountCode: z.string().max(32).optional(),
});

const billTemplateInput = z.object({
  description: z.string().min(1).max(2000),
  lineItems: z.array(lineItemInput).min(1),
  taxKobo: z.number().int().nonnegative().optional(),
});

const frequencySchema = z.enum(["weekly", "monthly", "quarterly"]);

// ─── Router ───────────────────────────────────────────────────────────────────

export const apRecurringRouter = router({
  /** Create a recurring bill schedule (idempotent). */
  createSchedule: protectedProcedure
    .input(z.object({
      vendorId: z.string().max(64).nullish(),
      billTemplate: billTemplateInput,
      frequency: frequencySchema,
      startAt: z.coerce.date(),
      maxRuns: z.number().int().positive().nullish(),
      maxAmountKobo: z.number().int().positive().nullish(),
      autoApproveBelowKobo: z.number().int().nonnegative().nullish(),
      idempotencyKey: idempotencyKeySchema,
    }))
    .mutation(async ({ ctx, input }) => {
      const { user, merchant } = await resolveMerchant(ctx.user.openId);
      return withIdempotency({
        key: input.idempotencyKey,
        merchantId: merchant.id,
        operation: "ap.recurring.create",
        requestBody: input,
        execute: async () => {
          const db = await requireDb();
          const nextRunAt = computeFirstNextRunAt(input.frequency, input.startAt);
          const [schedule] = await db.insert(apRecurringSchedules).values({
            merchantId: merchant.id,
            vendorId: input.vendorId ?? null,
            billTemplate: input.billTemplate,
            frequency: input.frequency,
            nextRunAt,
            isActive: true,
            maxRuns: input.maxRuns ?? null,
            maxAmountKobo: input.maxAmountKobo ?? null,
            autoApproveBelowKobo: input.autoApproveBelowKobo ?? null,
            createdBy: user.id,
          }).returning();
          await publishScheduleEvent("ap_recurring.schedule_created", merchant.id, schedule.id, {
            frequency: input.frequency, nextRunAt: nextRunAt.toISOString(),
          });
          await auditSchedule(ctx, merchant.id, "ap_recurring.schedule_created", schedule.id, {
            vendorId: input.vendorId ?? null, frequency: input.frequency,
            nextRunAt: nextRunAt.toISOString(),
          });
          return { schedule };
        },
      });
    }),

  /** List the merchant's recurring schedules. */
  listSchedules: protectedProcedure
    .input(z.object({
      isActive: z.boolean().optional(),
      vendorId: z.string().max(64).optional(),
      limit: z.number().int().min(1).max(200).default(50),
      offset: z.number().int().min(0).default(0),
    }))
    .query(async ({ ctx, input }) => {
      const { merchant } = await resolveMerchant(ctx.user.openId);
      const db = await requireDb();
      const conds = [eq(apRecurringSchedules.merchantId, merchant.id)];
      if (input.isActive !== undefined) conds.push(eq(apRecurringSchedules.isActive, input.isActive));
      if (input.vendorId) conds.push(eq(apRecurringSchedules.vendorId, input.vendorId));
      const schedules = await db
        .select()
        .from(apRecurringSchedules)
        .where(and(...conds))
        .orderBy(desc(apRecurringSchedules.createdAt))
        .limit(input.limit)
        .offset(input.offset);
      return { schedules };
    }),

  /** Fetch one schedule (merchant-scoped). */
  getSchedule: protectedProcedure
    .input(z.object({ scheduleId: z.number().int().positive() }))
    .query(async ({ ctx, input }) => {
      const { merchant } = await resolveMerchant(ctx.user.openId);
      const db = await requireDb();
      const [schedule] = await db
        .select()
        .from(apRecurringSchedules)
        .where(and(
          eq(apRecurringSchedules.id, input.scheduleId),
          eq(apRecurringSchedules.merchantId, merchant.id),
        ))
        .limit(1);
      if (!schedule) throw new TRPCError({ code: "NOT_FOUND", message: "Schedule not found" });
      return { schedule };
    }),

  /**
   * Update mutable schedule fields only (is_active, max_amount_kobo,
   * auto_approve_below_kobo, next_run_at). Template/frequency/vendor are
   * immutable — cancel and recreate to change them. Guarded UPDATE ...
   * WHERE id AND merchantId RETURNING (ownership folded into the write).
   */
  updateSchedule: protectedProcedure
    .input(z.object({
      scheduleId: z.number().int().positive(),
      isActive: z.boolean().optional(),
      maxAmountKobo: z.number().int().positive().nullish(),
      autoApproveBelowKobo: z.number().int().nonnegative().nullish(),
      nextRunAt: z.coerce.date().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      const { merchant } = await resolveMerchant(ctx.user.openId);
      const db = await requireDb();
      const set: Record<string, unknown> = {};
      if (input.isActive !== undefined) set.isActive = input.isActive;
      // nullish (not optional) so a client can explicitly CLEAR a limit with null
      if (input.maxAmountKobo !== undefined) set.maxAmountKobo = input.maxAmountKobo;
      if (input.autoApproveBelowKobo !== undefined) set.autoApproveBelowKobo = input.autoApproveBelowKobo;
      if (input.nextRunAt !== undefined) set.nextRunAt = input.nextRunAt;
      if (Object.keys(set).length === 0) {
        throw new TRPCError({ code: "BAD_REQUEST", message: "No updatable fields provided" });
      }
      const [schedule] = await db
        .update(apRecurringSchedules)
        .set(set)
        .where(and(
          eq(apRecurringSchedules.id, input.scheduleId),
          eq(apRecurringSchedules.merchantId, merchant.id),
        ))
        .returning();
      if (!schedule) throw new TRPCError({ code: "NOT_FOUND", message: "Schedule not found" });
      await auditSchedule(ctx, merchant.id, "ap_recurring.schedule_updated", schedule.id, { set });
      return { schedule };
    }),

  /** Cancel a schedule — guarded is_active flip (active → inactive). */
  cancelSchedule: protectedProcedure
    .input(z.object({ scheduleId: z.number().int().positive() }))
    .mutation(async ({ ctx, input }) => {
      const { merchant } = await resolveMerchant(ctx.user.openId);
      const db = await requireDb();
      const [schedule] = await db
        .update(apRecurringSchedules)
        .set({ isActive: false })
        .where(and(
          eq(apRecurringSchedules.id, input.scheduleId),
          eq(apRecurringSchedules.merchantId, merchant.id),
          eq(apRecurringSchedules.isActive, true),
        ))
        .returning();
      if (!schedule) {
        // Distinguish "not yours" from "already cancelled".
        const [existing] = await db
          .select({ id: apRecurringSchedules.id })
          .from(apRecurringSchedules)
          .where(and(
            eq(apRecurringSchedules.id, input.scheduleId),
            eq(apRecurringSchedules.merchantId, merchant.id),
          ))
          .limit(1);
        if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Schedule not found" });
        throw new TRPCError({ code: "CONFLICT", message: "Schedule is already cancelled" });
      }
      await publishScheduleEvent("ap_recurring.schedule_cancelled", merchant.id, schedule.id);
      await auditSchedule(ctx, merchant.id, "ap_recurring.schedule_cancelled", schedule.id);
      return { schedule };
    }),

  /** Bills generated by a schedule (source_ref 'recurring:{scheduleId}:{runCount}'). */
  runHistory: protectedProcedure
    .input(z.object({
      scheduleId: z.number().int().positive(),
      limit: z.number().int().min(1).max(200).default(50),
      offset: z.number().int().min(0).default(0),
    }))
    .query(async ({ ctx, input }) => {
      const { merchant } = await resolveMerchant(ctx.user.openId);
      const db = await requireDb();
      const [schedule] = await db
        .select()
        .from(apRecurringSchedules)
        .where(and(
          eq(apRecurringSchedules.id, input.scheduleId),
          eq(apRecurringSchedules.merchantId, merchant.id),
        ))
        .limit(1);
      if (!schedule) throw new TRPCError({ code: "NOT_FOUND", message: "Schedule not found" });
      const bills = await db
        .select()
        .from(apBills)
        .where(and(
          eq(apBills.merchantId, merchant.id),
          like(apBills.sourceRef, `recurring:${input.scheduleId}:%`),
        ))
        .orderBy(desc(apBills.createdAt))
        .limit(input.limit)
        .offset(input.offset);
      return { schedule, bills };
    }),

  /**
   * Manually run ONE schedule NOW through the same core executor the cron
   * sweep uses. Claim-first (guarded run_count increment + next_run_at
   * advance), then generate the bill. If bill generation fails the claim
   * stays rolled forward — identical to the cron claim-slot semantic (the
   * slot is skipped and the merchant notified) so a retry can never create a
   * duplicate bill for the same slot.
   */
  triggerNow: protectedProcedure
    .input(z.object({
      scheduleId: z.number().int().positive(),
      idempotencyKey: idempotencyKeySchema,
    }))
    .mutation(async ({ ctx, input }) => {
      const { merchant } = await resolveMerchant(ctx.user.openId);
      return withIdempotency({
        key: input.idempotencyKey,
        merchantId: merchant.id,
        operation: "ap.recurring.trigger",
        requestBody: input,
        execute: async () => {
          const db = await requireDb();
          const now = new Date();

          // Pre-claim read: ownership + the slot being executed (the due
          // next_run_at when past-due, otherwise 'now' for a manual run).
          const [existing] = await db
            .select()
            .from(apRecurringSchedules)
            .where(and(
              eq(apRecurringSchedules.id, input.scheduleId),
              eq(apRecurringSchedules.merchantId, merchant.id),
            ))
            .limit(1);
          if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Schedule not found" });
          if (!existing.isActive) {
            throw new TRPCError({ code: "CONFLICT", message: "Schedule is inactive — reactivate it before triggering" });
          }
          const slotAt = existing.nextRunAt && existing.nextRunAt <= now ? existing.nextRunAt : now;

          // Claim: exactly one concurrent trigger/sweep can win this run_count
          // generation (runCount equality guard = optimistic concurrency).
          const [claimed] = await db
            .update(apRecurringSchedules)
            .set({
              nextRunAt: nextRunAdvanceExpr() as unknown as Date,
              lastRunAt: now,
              runCount: sql`${apRecurringSchedules.runCount} + 1` as unknown as number,
            })
            .where(and(
              eq(apRecurringSchedules.id, input.scheduleId),
              eq(apRecurringSchedules.merchantId, merchant.id),
              eq(apRecurringSchedules.isActive, true),
              eq(apRecurringSchedules.runCount, existing.runCount ?? 0),
              sql`(${apRecurringSchedules.maxRuns} IS NULL OR ${apRecurringSchedules.runCount} < ${apRecurringSchedules.maxRuns})`,
            ))
            .returning();
          if (!claimed) {
            throw new TRPCError({
              code: "CONFLICT",
              message: "Schedule changed concurrently or reached max runs — retry",
            });
          }

          const runNumber = claimed.runCount ?? (existing.runCount ?? 0) + 1;
          try {
            const result = await executeRecurringScheduleRun(db, {
              id: claimed.id,
              merchantId: claimed.merchantId,
              vendorId: claimed.vendorId,
              billTemplate: claimed.billTemplate,
              runCount: runNumber,
              maxAmountKobo: claimed.maxAmountKobo,
              autoApproveBelowKobo: claimed.autoApproveBelowKobo,
              createdBy: claimed.createdBy,
            }, { slotKey: `recurring:${claimed.id}:${slotAt.toISOString()}` });

            await publishScheduleEvent("ap_recurring.schedule_triggered", merchant.id, claimed.id, {
              runCount: runNumber, status: result.status, billId: result.billId,
            });
            await auditSchedule(ctx, merchant.id, "ap_recurring.schedule_triggered", claimed.id, {
              runCount: runNumber, status: result.status,
              billId: result.billId, totalKobo: result.totalKobo,
            });
            return { schedule: claimed, run: result };
          } catch (err: any) {
            // Claim already rolled forward (documented claim-slot semantic) —
            // notify the merchant and surface the failure; the next slot runs
            // normally. Never roll the claim back (duplicate-bill risk).
            logger.error("ap_recurring_trigger_failed", {
              scheduleId: claimed.id, error: err instanceof Error ? err.message : String(err),
            });
            await auditSchedule(ctx, merchant.id, "ap_recurring.trigger_failed", claimed.id, {
              runCount: runNumber, error: err instanceof Error ? err.message : String(err),
            });
            throw new TRPCError({
              code: "INTERNAL_SERVER_ERROR",
              message: `Recurring bill generation failed: ${err instanceof Error ? err.message : String(err)}`,
            });
          }
        },
      });
    }),
});

/** Pure internals exported for unit tests (spec D3). */
export const __apRecurringInternals = {
  addFrequency,
  computeFirstNextRunAt,
};
