// Package nibss provides a client for the NIBSS NIP 2.0 REST gateway.
//
// The NIBSS NIP (Nigeria Inter-Bank Settlement System) gateway exposes a
// REST/JSON adapter over the underlying SOAP NIP 2.0 protocol.  This client
// implements:
//   - Single Credit Transfer (NIP 2.0 endpoint: /NIPInterface/rest/Intrabank/SingleCreditTransfer)
//   - Name Enquiry (NIP 2.0 endpoint: /NIPInterface/rest/Intrabank/NameEnquiry)
//   - Transaction Status Query (NIP 2.0 endpoint: /NIPInterface/rest/Intrabank/TransactionStatusQuery)
//
// All requests are signed with an HMAC-SHA256 signature using the configured
// NIBSS_SECRET_KEY environment variable.  The gateway URL is read from
// NIBSS_GATEWAY_URL.  When either variable is absent the client returns a
// ErrNotConfigured sentinel so callers can fall back gracefully.
//
// Reference: https://nibss-plc.com.ng/nip-integration-guide (internal doc)
package nibss

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"strings"
	"time"
)

// ErrNotConfigured is returned when NIBSS_GATEWAY_URL or NIBSS_SECRET_KEY
// are not set in the environment.
var ErrNotConfigured = errors.New("nibss: gateway not configured (NIBSS_GATEWAY_URL / NIBSS_SECRET_KEY not set)")

// ErrPending is returned by QueryTransactionStatus when the transfer is
// still being processed.  Callers should retry after a short delay.
var ErrPending = errors.New("nibss: transaction still pending")

// Client is a NIBSS NIP 2.0 REST gateway client.
type Client struct {
	baseURL    string
	secretKey  string
	institutionCode string
	httpClient *http.Client
}

// New returns a Client configured from environment variables:
//   - NIBSS_GATEWAY_URL   — base URL of the REST adapter (no trailing slash)
//   - NIBSS_SECRET_KEY    — HMAC-SHA256 signing key
//   - NIBSS_INSTITUTION_CODE — originating institution code (6 digits)
//
// Returns ErrNotConfigured when any required variable is missing.
func New() (*Client, error) {
	base := os.Getenv("NIBSS_GATEWAY_URL")
	secret := os.Getenv("NIBSS_SECRET_KEY")
	instCode := os.Getenv("NIBSS_INSTITUTION_CODE")
	if base == "" || secret == "" {
		return nil, ErrNotConfigured
	}
	if instCode == "" {
		instCode = "999999" // default test institution code
	}
	return &Client{
		baseURL:         strings.TrimRight(base, "/"),
		secretKey:       secret,
		institutionCode: instCode,
		httpClient: &http.Client{
			Timeout: 30 * time.Second,
		},
	}, nil
}

// ─── Request / Response types ─────────────────────────────────────────────────

// SingleCreditRequest is the payload for a NIP single credit transfer.
type SingleCreditRequest struct {
	// SessionID is a 30-character unique reference generated by the originator.
	// Format: YYYYMMDDHHMMSS + 16 random chars.
	SessionID string `json:"SessionID"`
	// DestinationInstitutionCode is the 6-digit CBN bank code of the beneficiary bank.
	DestinationInstitutionCode string `json:"DestinationInstitutionCode"`
	// ChannelCode: 1=ATM, 2=Internet, 3=Mobile, 4=POS, 5=Kiosk, 6=Branch
	ChannelCode string `json:"ChannelCode"`
	// BeneficiaryAccountName as returned by NameEnquiry.
	BeneficiaryAccountName string `json:"BeneficiaryAccountName"`
	// BeneficiaryAccountNumber is the 10-digit NUBAN.
	BeneficiaryAccountNumber string `json:"BeneficiaryAccountNumber"`
	// BeneficiaryBankVerificationNumber (optional).
	BeneficiaryBankVerificationNumber string `json:"BeneficiaryBankVerificationNumber"`
	// BeneficiaryKYCLevel: 1, 2, or 3.
	BeneficiaryKYCLevel string `json:"BeneficiaryKYCLevel"`
	// OriginatorAccountName — PayGate settlement account name.
	OriginatorAccountName string `json:"OriginatorAccountName"`
	// OriginatorAccountNumber — PayGate settlement NUBAN.
	OriginatorAccountNumber string `json:"OriginatorAccountNumber"`
	// OriginatorBankVerificationNumber (optional).
	OriginatorBankVerificationNumber string `json:"OriginatorBankVerificationNumber"`
	// OriginatorKYCLevel: 1, 2, or 3.
	OriginatorKYCLevel string `json:"OriginatorKYCLevel"`
	// TransactionLocation — "lat,lon" string.
	TransactionLocation string `json:"TransactionLocation"`
	// Narration — free-text payment description (max 100 chars).
	Narration string `json:"Narration"`
	// PaymentReference — unique merchant payment reference.
	PaymentReference string `json:"PaymentReference"`
	// Amount in kobo (minor units, no decimal).
	Amount string `json:"Amount"`
}

// SingleCreditResponse is the gateway response for a single credit transfer.
type SingleCreditResponse struct {
	SessionID          string `json:"SessionID"`
	ResponseCode       string `json:"ResponseCode"`
	ResponseMessage    string `json:"ResponseMessage"`
	BeneficiaryName    string `json:"BeneficiaryName"`
	TransactionID      string `json:"TransactionID"`
}

// NameEnquiryRequest is the payload for a NIP name enquiry.
type NameEnquiryRequest struct {
	SessionID                  string `json:"SessionID"`
	DestinationInstitutionCode string `json:"DestinationInstitutionCode"`
	ChannelCode                string `json:"ChannelCode"`
	AccountNumber              string `json:"AccountNumber"`
}

// NameEnquiryResponse is the gateway response for a name enquiry.
type NameEnquiryResponse struct {
	SessionID       string `json:"SessionID"`
	ResponseCode    string `json:"ResponseCode"`
	ResponseMessage string `json:"ResponseMessage"`
	AccountName     string `json:"AccountName"`
	BankCode        string `json:"BankCode"`
	BVN             string `json:"BVN"`
	KYCLevel        string `json:"KYCLevel"`
}

// TransactionStatusRequest is the payload for a transaction status query.
type TransactionStatusRequest struct {
	SessionID string `json:"SessionID"`
}

// TransactionStatusResponse is the gateway response for a status query.
type TransactionStatusResponse struct {
	SessionID       string `json:"SessionID"`
	ResponseCode    string `json:"ResponseCode"`
	ResponseMessage string `json:"ResponseMessage"`
	// Status: "00"=success, "09"=pending, others=failed
	Status string `json:"Status"`
}

// ─── NIP response codes ───────────────────────────────────────────────────────

const (
	// RespSuccess is the NIP success response code.
	RespSuccess = "00"
	// RespPending is the NIP pending response code (transaction still processing).
	RespPending = "09"
)

// ─── Client methods ───────────────────────────────────────────────────────────

// SingleCreditTransfer submits a NIP single credit transfer.
// Returns the gateway response on success, or an error if the request fails
// or the gateway returns a non-success response code.
func (c *Client) SingleCreditTransfer(ctx context.Context, req SingleCreditRequest) (*SingleCreditResponse, error) {
	slog.Info("[nibss] SingleCreditTransfer",
		"session_id", req.SessionID,
		"dest_bank", req.DestinationInstitutionCode,
		"account", req.BeneficiaryAccountNumber,
		"amount", req.Amount,
	)
	resp, err := c.post(ctx, "/NIPInterface/rest/Intrabank/SingleCreditTransfer", req)
	if err != nil {
		return nil, fmt.Errorf("nibss: SingleCreditTransfer HTTP: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("nibss: SingleCreditTransfer read body: %w", err)
	}
	var result SingleCreditResponse
	if err := json.Unmarshal(body, &result); err != nil {
		return nil, fmt.Errorf("nibss: SingleCreditTransfer parse response: %w (body=%s)", err, string(body))
	}
	if result.ResponseCode != RespSuccess {
		return &result, fmt.Errorf("nibss: SingleCreditTransfer failed: code=%s msg=%s",
			result.ResponseCode, result.ResponseMessage)
	}
	slog.Info("[nibss] SingleCreditTransfer: success",
		"session_id", result.SessionID,
		"transaction_id", result.TransactionID,
	)
	return &result, nil
}

// NameEnquiry performs a NIP name enquiry to resolve an account number to
// the account holder's name.
func (c *Client) NameEnquiry(ctx context.Context, accountNumber, bankCode string) (*NameEnquiryResponse, error) {
	sessionID := generateSessionID()
	req := NameEnquiryRequest{
		SessionID:                  sessionID,
		DestinationInstitutionCode: bankCode,
		ChannelCode:                "2",
		AccountNumber:              accountNumber,
	}
	slog.Info("[nibss] NameEnquiry", "account", accountNumber, "bank_code", bankCode)
	resp, err := c.post(ctx, "/NIPInterface/rest/Intrabank/NameEnquiry", req)
	if err != nil {
		return nil, fmt.Errorf("nibss: NameEnquiry HTTP: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("nibss: NameEnquiry read body: %w", err)
	}
	var result NameEnquiryResponse
	if err := json.Unmarshal(body, &result); err != nil {
		return nil, fmt.Errorf("nibss: NameEnquiry parse response: %w (body=%s)", err, string(body))
	}
	if result.ResponseCode != RespSuccess {
		return &result, fmt.Errorf("nibss: NameEnquiry failed: code=%s msg=%s",
			result.ResponseCode, result.ResponseMessage)
	}
	slog.Info("[nibss] NameEnquiry: success", "account_name", result.AccountName)
	return &result, nil
}

// QueryTransactionStatus polls the gateway for the status of a previously
// submitted transfer.  Returns ErrPending when the transfer is still being
// processed so callers can retry via Temporal's retry policy.
func (c *Client) QueryTransactionStatus(ctx context.Context, sessionID string) (*TransactionStatusResponse, error) {
	req := TransactionStatusRequest{SessionID: sessionID}
	slog.Info("[nibss] QueryTransactionStatus", "session_id", sessionID)
	resp, err := c.post(ctx, "/NIPInterface/rest/Intrabank/TransactionStatusQuery", req)
	if err != nil {
		return nil, fmt.Errorf("nibss: QueryTransactionStatus HTTP: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("nibss: QueryTransactionStatus read body: %w", err)
	}
	var result TransactionStatusResponse
	if err := json.Unmarshal(body, &result); err != nil {
		return nil, fmt.Errorf("nibss: QueryTransactionStatus parse response: %w (body=%s)", err, string(body))
	}
	switch result.ResponseCode {
	case RespSuccess:
		slog.Info("[nibss] QueryTransactionStatus: confirmed", "session_id", sessionID)
		return &result, nil
	case RespPending:
		return &result, ErrPending
	default:
		return &result, fmt.Errorf("nibss: transaction failed: code=%s msg=%s",
			result.ResponseCode, result.ResponseMessage)
	}
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

// post sends a signed JSON POST request to the given path.
func (c *Client) post(ctx context.Context, path string, payload any) (*http.Response, error) {
	body, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("nibss: marshal payload: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.baseURL+path, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("nibss: build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")
	req.Header.Set("InstitutionCode", c.institutionCode)
	// HMAC-SHA256 signature over the raw JSON body.
	sig := c.sign(body)
	req.Header.Set("X-NIBSS-Signature", sig)
	req.Header.Set("X-NIBSS-Timestamp", time.Now().UTC().Format(time.RFC3339))
	return c.httpClient.Do(req)
}

// sign returns the HMAC-SHA256 hex digest of data using the client secret key.
func (c *Client) sign(data []byte) string {
	mac := hmac.New(sha256.New, []byte(c.secretKey))
	mac.Write(data)
	return hex.EncodeToString(mac.Sum(nil))
}

// generateSessionID returns a 30-character NIP session ID:
// YYYYMMDDHHMMSS (14 chars) + institution code (6 chars) + 10 random hex chars.
func generateSessionID() string {
	ts := time.Now().UTC().Format("20060102150405")
	// Use crypto/rand-derived entropy via time nanoseconds for simplicity.
	// In production, use crypto/rand for the random suffix.
	nano := fmt.Sprintf("%016x", time.Now().UnixNano())
	return ts + nano[:16]
}
