apiVersion: v1
kind: ServiceAccount
metadata:
  name: paygate-portal
  namespace: paygate
  labels:
    app: paygate-merchant-portal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paygate-portal-role
  namespace: paygate
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: ["paygate-secrets"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paygate-portal-rolebinding
  namespace: paygate
subjects:
  - kind: ServiceAccount
    name: paygate-portal
    namespace: paygate
roleRef:
  kind: Role
  name: paygate-portal-role
  apiGroup: rbac.authorization.k8s.io
