"""
NextHub Billing Invoice Generator
==================================
Generates PDF invoices for DFSPs covering:
  - Scheme fees (per-transfer)
  - Interchange (DFSP-to-DFSP)
  - FX markup
  - Penalty fees (late settlement, rejected disputes)

The invoice is generated by the Temporal `MonthlyBillingWorkflow`
and uploaded to S3. The S3 URL is stored in the `billing_invoices` table.

Dependencies:
  pip install reportlab boto3
"""

from __future__ import annotations

import io
import os
from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Optional

# ReportLab imports
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    HRFlowable,
)


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

@dataclass
class FeeLineItem:
    description: str
    quantity: int
    unit_amount_minor: int   # In minor units (kobo)
    total_minor: int
    fee_type: str            # "SCHEME_FEE" | "INTERCHANGE" | "FX_MARKUP" | "PENALTY"


@dataclass
class InvoiceData:
    invoice_number: str
    dfsp_id: str
    dfsp_name: str
    billing_period_start: date
    billing_period_end: date
    line_items: list[FeeLineItem]
    currency: str = "NGN"
    generated_at: datetime = field(default_factory=datetime.utcnow)
    scheme_operator: str = "NextHub Scheme Operator"
    scheme_operator_address: str = "Lagos, Nigeria"

    @property
    def subtotal_minor(self) -> int:
        return sum(item.total_minor for item in self.line_items)

    @property
    def vat_minor(self) -> int:
        # 7.5% VAT (Nigeria)
        return int(self.subtotal_minor * 0.075)

    @property
    def total_minor(self) -> int:
        return self.subtotal_minor + self.vat_minor

    def format_amount(self, minor: int) -> str:
        """Format minor units as currency string (e.g. ₦1,234.56)."""
        symbol = {"NGN": "₦", "USD": "$", "GHS": "₵", "KES": "KSh"}.get(self.currency, "")
        major = minor / 100
        return f"{symbol}{major:,.2f}"


# ---------------------------------------------------------------------------
# Invoice generator
# ---------------------------------------------------------------------------

class InvoiceGenerator:
    """Generates PDF invoices for NextHub DFSP billing."""

    # Brand colours
    PRIMARY_COLOR = colors.HexColor("#1a1a2e")
    ACCENT_COLOR = colors.HexColor("#e94560")
    LIGHT_GRAY = colors.HexColor("#f8f9fa")
    MID_GRAY = colors.HexColor("#6c757d")

    def generate_pdf(self, invoice: InvoiceData) -> bytes:
        """
        Generate a PDF invoice and return the raw bytes.

        The caller is responsible for uploading to S3 and storing the URL.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=20 * mm,
            leftMargin=20 * mm,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
        )

        styles = getSampleStyleSheet()
        story = []

        # ── Header ────────────────────────────────────────────────────────────
        story.append(self._build_header(invoice, styles))
        story.append(Spacer(1, 8 * mm))
        story.append(HRFlowable(width="100%", thickness=2, color=self.ACCENT_COLOR))
        story.append(Spacer(1, 6 * mm))

        # ── Billing details ───────────────────────────────────────────────────
        story.append(self._build_billing_details(invoice, styles))
        story.append(Spacer(1, 8 * mm))

        # ── Line items table ──────────────────────────────────────────────────
        story.append(Paragraph("Fee Details", styles["Heading2"]))
        story.append(Spacer(1, 4 * mm))
        story.append(self._build_line_items_table(invoice))
        story.append(Spacer(1, 6 * mm))

        # ── Totals ────────────────────────────────────────────────────────────
        story.append(self._build_totals_table(invoice))
        story.append(Spacer(1, 8 * mm))

        # ── Footer ────────────────────────────────────────────────────────────
        story.append(HRFlowable(width="100%", thickness=1, color=self.MID_GRAY))
        story.append(Spacer(1, 4 * mm))
        story.append(self._build_footer(invoice, styles))

        doc.build(story)
        return buffer.getvalue()

    def _build_header(self, invoice: InvoiceData, styles) -> Table:
        title_style = ParagraphStyle(
            "InvoiceTitle",
            parent=styles["Heading1"],
            fontSize=24,
            textColor=self.PRIMARY_COLOR,
            spaceAfter=4,
        )
        subtitle_style = ParagraphStyle(
            "InvoiceSubtitle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=self.MID_GRAY,
        )
        data = [[
            Paragraph("NEXTHUB", title_style),
            Paragraph(
                f"<b>INVOICE</b><br/>"
                f"<font color='#{self.MID_GRAY.hexval()[2:]}' size='9'>"
                f"#{invoice.invoice_number}</font>",
                ParagraphStyle("Right", parent=styles["Normal"], alignment=2, fontSize=14),
            ),
        ]]
        t = Table(data, colWidths=["60%", "40%"])
        t.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")]))
        return t

    def _build_billing_details(self, invoice: InvoiceData, styles) -> Table:
        label_style = ParagraphStyle(
            "Label", parent=styles["Normal"], fontSize=8,
            textColor=self.MID_GRAY, spaceAfter=2,
        )
        value_style = ParagraphStyle(
            "Value", parent=styles["Normal"], fontSize=10,
            textColor=self.PRIMARY_COLOR,
        )
        period = (
            f"{invoice.billing_period_start.strftime('%d %b %Y')} – "
            f"{invoice.billing_period_end.strftime('%d %b %Y')}"
        )
        data = [
            [
                [Paragraph("FROM", label_style),
                 Paragraph(invoice.scheme_operator, value_style),
                 Paragraph(invoice.scheme_operator_address, value_style)],
                [Paragraph("TO", label_style),
                 Paragraph(invoice.dfsp_name, value_style),
                 Paragraph(f"DFSP ID: {invoice.dfsp_id}", value_style)],
                [Paragraph("BILLING PERIOD", label_style),
                 Paragraph(period, value_style)],
                [Paragraph("GENERATED", label_style),
                 Paragraph(invoice.generated_at.strftime("%d %b %Y %H:%M UTC"), value_style)],
            ]
        ]
        t = Table(data, colWidths=["25%", "30%", "25%", "20%"])
        t.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BACKGROUND", (0, 0), (-1, -1), self.LIGHT_GRAY),
            ("ROWPADDING", (0, 0), (-1, -1), 8),
        ]))
        return t

    def _build_line_items_table(self, invoice: InvoiceData) -> Table:
        headers = ["Description", "Type", "Qty", "Unit Amount", "Total"]
        rows = [headers]
        for item in invoice.line_items:
            rows.append([
                item.description,
                item.fee_type.replace("_", " "),
                str(item.quantity),
                invoice.format_amount(item.unit_amount_minor),
                invoice.format_amount(item.total_minor),
            ])

        t = Table(rows, colWidths=["35%", "18%", "8%", "18%", "21%"])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), self.PRIMARY_COLOR),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, self.LIGHT_GRAY]),
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dee2e6")),
            ("ROWPADDING", (0, 0), (-1, -1), 6),
        ]))
        return t

    def _build_totals_table(self, invoice: InvoiceData) -> Table:
        rows = [
            ["", "Subtotal:", invoice.format_amount(invoice.subtotal_minor)],
            ["", f"VAT (7.5%):", invoice.format_amount(invoice.vat_minor)],
            ["", "TOTAL DUE:", invoice.format_amount(invoice.total_minor)],
        ]
        t = Table(rows, colWidths=["55%", "25%", "20%"])
        t.setStyle(TableStyle([
            ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
            ("FONTNAME", (1, 2), (-1, 2), "Helvetica-Bold"),
            ("FONTSIZE", (1, 2), (-1, 2), 12),
            ("TEXTCOLOR", (1, 2), (-1, 2), self.ACCENT_COLOR),
            ("LINEABOVE", (1, 2), (-1, 2), 1.5, self.PRIMARY_COLOR),
            ("ROWPADDING", (0, 0), (-1, -1), 5),
        ]))
        return t

    def _build_footer(self, invoice: InvoiceData, styles) -> Paragraph:
        footer_style = ParagraphStyle(
            "Footer", parent=styles["Normal"], fontSize=8,
            textColor=self.MID_GRAY, alignment=1,
        )
        return Paragraph(
            f"This invoice is generated automatically by NextHub SRBE. "
            f"Payment is due within 5 business days of the billing period end. "
            f"Disputes must be raised within 10 business days. "
            f"Invoice #{invoice.invoice_number} | {invoice.scheme_operator}",
            footer_style,
        )


# ---------------------------------------------------------------------------
# Convenience function
# ---------------------------------------------------------------------------

def generate_invoice_pdf(invoice: InvoiceData) -> bytes:
    """Generate a PDF invoice and return raw bytes."""
    return InvoiceGenerator().generate_pdf(invoice)
